// Shared module-description types: same shape lowarc/Bootstrap already uses, and the same shape
// project.json's preset list reuses (Dependency = {id, version}), so a project's "requires" and a
// module's "requires" are literally the same schema at two different levels.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use serde_json::Value;

/// Where a module with no stated priority sorts. Middling on purpose, so an unset module can be
/// pushed either side of by one that does state a priority.
pub const DEFAULT_PRIORITY: i32 = 100;

#[derive(Debug, Default, Deserialize, Serialize, Clone)]
#[serde(default)]
pub struct Dependency {
    /// The module this depends on, by manifest id. `"module"` is accepted as a spelling of the
    /// same field so a manifest can say which KIND of thing it means without the reader having to
    /// infer it — `{"module": "vector-canvas"}` and `{"id": "vector-canvas"}` are identical, and
    /// the explicit spelling is the one to prefer in anything newly written.
    #[serde(alias = "module")]
    pub id: String,
    /// A CONTRACT this depends on, instead of a specific module: "I read whatever provides this,"
    /// where a plain id means "I depend on this exact implementation." Contracts are themselves
    /// modules (kind: "contract"), so this resolves through the same store and the same version
    /// check; what differs is that the consumer then reads the published state of every module
    /// that PROVIDES it, not the contract's own (a contract publishes nothing — it has no process).
    /// Mutually exclusive with `id`; setting both is rejected by project::resolve rather than
    /// silently resolving one of them.
    pub contract: String,
    /// A RANGE, not a version, despite the name: "^1", ">=2.1", "*". Called `version` because that
    /// is what a dependency's range is called in every manifest format anyone has used before this
    /// one (Cargo's `serde = { version = "1.0" }` is the same range-called-version). Compare with
    /// Manifest::version and Provision::version, both of which are single concrete versions.
    ///
    /// Checked against the resolved module's own version by project::check_versions.
    pub version: String,
    /// False (the default): project::resolve() fails the run if this is not installed. True: a
    /// module that cooperates with another IF present, reading its published state, but has no
    /// structural need for it, so resolve() leaves it out rather than erroring.
    ///
    /// Only meaningful on a MODULE's requires. A project's own top-level requires is always
    /// mandatory, since listing something there already means the author wants it.
    pub optional: bool,
    /// Anything in the JSON this struct has no field for. Captured rather than dropped so a
    /// misspelling ("verison" for "version") can be reported: silently parsing to a default is how a manifest ends
    /// up looking correct while doing nothing. Kept permissive rather than rejected outright so a
    /// manifest written for a newer Studio still loads here.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

impl Dependency {
    /// What this entry actually names in the module store. A contract requirement resolves to the
    /// contract module itself (that's what gets version-checked and installed); which modules end
    /// up PROVIDING it is a separate, runtime question. See `providers_of` below.
    pub fn store_id(&self) -> &str {
        if self.id.is_empty() {
            &self.contract
        } else {
            &self.id
        }
    }

    /// The range this requirement will accept, or the reason it could not be read.
    ///
    /// An empty `version` means the same as `"*"`. That is not laxness for its own sake: a
    /// requirement written before ranges meant anything says `"*"`, and a preset generated by
    /// Studio still does, so both have to keep meaning "any version, including a module that
    /// declares none".
    pub fn range(&self) -> Result<semver::VersionReq, String> {
        if self.version.trim().is_empty() {
            return Ok(semver::VersionReq::STAR);
        }
        semver::VersionReq::parse(&self.version).map_err(|e| format!("\"{}\" is not a version range: {e}", self.version))
    }

    /// Whether this requirement NAMES a contract, as opposed to naming a module. Deliberately not
    /// called is_contract: Manifest::is_contract means "I am a contract", and a requirement is
    /// never one of those, it only points at one.
    pub fn names_contract(&self) -> bool {
        self.id.is_empty() && !self.contract.is_empty()
    }

    /// A manifest that sets both `id` and `contract` means two different things at once, and there
    /// is no reading of it that is obviously right. Reported rather than resolved.
    pub fn names_both(&self) -> bool {
        !self.id.is_empty() && !self.contract.is_empty()
    }
}

/// One contract a module declares it speaks. Being listed here is the ONLY thing that makes a
/// module eligible to fill a role, which is the whole point of the change this type exists for.
/// Before it, the only way to fill a role was to be NAMED the role (a module publishing under its
/// own id meant `shared.director.draw` required a module whose id was literally "director"), so
/// there could only ever be one of anything, and a module could not take a job without renaming
/// itself into it.
#[derive(Debug, Default, Deserialize, Serialize, Clone)]
#[serde(default)]
pub struct Provision {
    pub contract: String,
    /// The single concrete version of the contract this module implements ("1.0.0"), not a range.
    /// A provider states what it speaks; a consumer's Dependency::version states what it will
    /// accept. NOT yet matched against each other: a requirement's range is checked against the
    /// contract module's own version, but nothing yet checks that a given PROVIDER speaks a
    /// dialect a given consumer accepts. See docs/modules.md on why that one is a design question.
    pub version: String,
    /// Anything in the JSON this struct has no field for. Captured rather than dropped so a
    /// misspelling ("contarct" for "contract") can be reported: silently parsing to a default is how a manifest ends
    /// up looking correct while doing nothing. Kept permissive rather than rejected outright so a
    /// manifest written for a newer Studio still loads here.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Deserialize)]
#[serde(default)]
pub struct Manifest {
    pub id: String,
    pub name: String,
    /// Tiebreak among modules that no `requires` relationship orders against each other, low
    /// first. Not an order in its own right: `requires` always wins, so this only decides between
    /// modules where nothing else has an opinion (see run_order). Unset means no opinion, which is
    /// the honest answer for most modules and for every contract, since a contract never runs.
    pub priority: Option<i32>,
    pub requires: Vec<Dependency>,
    /// Contracts this module speaks. See Provision.
    pub provides: Vec<Provision>,
    /// `"contract"` marks a manifest that DEFINES a vocabulary rather than implementing anything.
    /// It resolves and version-checks like any other module. Contracts are modules, which is what
    /// lets them install and distribute through machinery that already exists, but it has no
    /// process, so the runtime never spawns it and it never publishes anything of its own. Any
    /// other value (or none) means an ordinary module.
    pub kind: Option<String>,
    /// This module's own version. Shown in the Modules manage page, and what every requirement
    /// naming this module is matched against (see project::check_versions). Optional because a
    /// module nobody asks for by range never needs one; a real range against a module without one
    /// is an error rather than a pass.
    pub version: Option<String>,
    pub description: Option<String>,
    /// Purely descriptive, shown in the Modules manage page's detail header: no marketplace
    /// exists yet to link out to, but a locally-authored module can still point at its own repo.
    pub website: Option<String>,
    /// Path to an SVG/PNG within this module's own folder, read the same way a plugin's rail icon
    /// is (see plugin_assets/loadRailIconSvg): a missing/absent icon falls back to a generic
    /// placeholder on the frontend rather than this field being required.
    pub icon: Option<String>,
    /// Anything in the JSON this struct has no field for. Captured rather than dropped so a
    /// misspelling ("provdies" for "provides") can be reported: silently parsing to a default is how a manifest ends
    /// up looking correct while doing nothing. Kept permissive rather than rejected outright so a
    /// manifest written for a newer Studio still loads here.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

impl Default for Manifest {
    fn default() -> Self {
        Self {
            id: String::new(),
            name: "Unnamed Module".into(),
            priority: None,
            requires: Vec::new(),
            provides: Vec::new(),
            kind: None,
            version: None,
            description: None,
            website: None,
            icon: None,
            extra: HashMap::new(),
        }
    }
}

impl Manifest {
    /// Err carries the reason, which serde already knows down to the line and column. Returning
    /// Option threw that away and left every caller saying "unreadable", which is true and useless
    /// to whoever has to go fix the file.
    pub fn read(folder: &Path) -> Result<Self, String> {
        let path = folder.join("manifest.json");
        let text = std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
        serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))
    }

    /// The one value `kind` may hold, besides being absent. An unrecognised kind is an error
    /// rather than a shrug: unknown FIELDS are safe to ignore, but an unknown kind decides whether
    /// this thing gets run, and guessing "ordinary module" for something that calls itself
    /// something else can spawn a process that was never meant to be one.
    pub fn invalid_kind(&self) -> Option<&str> {
        match self.kind.as_deref() {
            None | Some("contract") => None,
            Some(other) => Some(other),
        }
    }

    /// Every field in this manifest that nothing reads, labelled by where it sits. Empty for a
    /// manifest with no typos in it, which is the normal case.
    pub fn unknown_fields(&self) -> Vec<String> {
        let mut found: Vec<String> = self.extra.keys().map(|k| k.to_string()).collect();
        for (i, dep) in self.requires.iter().enumerate() {
            found.extend(dep.extra.keys().map(|k| format!("requires[{i}].{k}")));
        }
        for (i, prov) in self.provides.iter().enumerate() {
            found.extend(prov.extra.keys().map(|k| format!("provides[{i}].{k}")));
        }
        found.sort();
        found
    }

    /// A definition rather than an implementation: resolved and version-checked, never run.
    pub fn is_contract(&self) -> bool {
        self.kind.as_deref() == Some("contract")
    }

    pub fn provides_contract(&self, contract: &str) -> bool {
        self.provides.iter().any(|p| p.contract == contract)
    }

    /// This module's own version as something comparable, or None when it declares none or
    /// declares something that is not a version. Both cases are only an error once something
    /// actually asks for a range; see check_versions.
    pub fn declared_version(&self) -> Option<semver::Version> {
        semver::Version::parse(self.version.as_deref()?.trim()).ok()
    }
}

/// Which of `infos` provide `contract`, in the order given: callers pass an already-ranked list,
/// so the result is in run order, which is what makes a gathered contract's array meaningful
/// (draw order is list order, so run order is z-order).
pub fn providers_of<'a>(infos: &[&'a ModuleInfo], contract: &str) -> Vec<&'a ModuleInfo> {
    infos.iter().copied().filter(|i| i.manifest.provides_contract(contract)).collect()
}

#[derive(Debug)]
pub struct ModuleInfo {
    pub folder: PathBuf,
    pub manifest: Manifest,
}

/// Post-order DFS over Requires, seeded by LoadOrder, as each id's RANK in that walk (0 = runs
/// first) rather than a reordered Vec: for a caller that only has borrowed ModuleInfos to work
/// with (process_module::spawn_and_run, which doesn't own the list it was handed, so it can't
/// consume-and-rebuild it the way in_run_order below does; takes `&[&ModuleInfo]`, not
/// `&[ModuleInfo]`, specifically so that caller can pass borrowed references straight through).
/// Both share this exact same walk; in_run_order is just the by-value convenience on top of
/// it for a caller that does own its Vec. Identical to Bootstrap's launch_config::order_by_requires:
/// a module loads after everything it requires, tolerant of cycles and missing ids.
pub fn run_order(infos: &[&ModuleInfo]) -> std::collections::HashMap<String, usize> {
    let mut priority_seed: Vec<usize> = (0..infos.len()).collect();
    priority_seed.sort_by_key(|&i| infos[i].manifest.priority.unwrap_or(DEFAULT_PRIORITY));

    let by_id: std::collections::HashMap<String, usize> = priority_seed
        .iter()
        .filter(|&&i| !infos[i].manifest.id.is_empty())
        .map(|&i| (infos[i].manifest.id.clone(), i))
        .collect();

    let mut seen = vec![false; infos.len()];
    let mut order = Vec::with_capacity(infos.len());

    fn visit(
        idx: usize,
        infos: &[&ModuleInfo],
        by_id: &std::collections::HashMap<String, usize>,
        seen: &mut [bool],
        order: &mut Vec<usize>,
    ) {
        if seen[idx] {
            return;
        }
        seen[idx] = true;
        for req in &infos[idx].manifest.requires {
            if req.store_id().is_empty() {
                continue;
            }
            // A contract requirement has to order this module after everything that PROVIDES the
            // contract, not merely after the contract's own definition: the definition has no
            // process and publishes nothing, so ordering against it would guarantee nothing. This
            // is what keeps the shared/publish rule true for contracts: a consumer's frame sees
            // this tick's output from every provider, not last tick's.
            if req.names_contract() {
                for (dep_idx, info) in infos.iter().enumerate() {
                    if dep_idx != idx && info.manifest.provides_contract(&req.contract) {
                        visit(dep_idx, infos, by_id, seen, order);
                    }
                }
            }
            if let Some(&dep_idx) = by_id.get(req.store_id()) {
                if dep_idx != idx {
                    visit(dep_idx, infos, by_id, seen, order);
                }
            }
        }
        order.push(idx);
    }

    for &idx in &priority_seed {
        visit(idx, infos, &by_id, &mut seen, &mut order);
    }

    order.into_iter().enumerate().map(|(rank, idx)| (infos[idx].manifest.id.clone(), rank)).collect()
}

/// By-value convenience over run_order, for a caller that owns its Vec and wants it physically
/// reordered rather than just ranked.
pub fn in_run_order(mut infos: Vec<ModuleInfo>) -> Vec<ModuleInfo> {
    let refs: Vec<&ModuleInfo> = infos.iter().collect();
    let rank = run_order(&refs);
    infos.sort_by_key(|i| rank.get(&i.manifest.id).copied().unwrap_or(usize::MAX));
    infos
}

#[cfg(test)]
mod tests {
    use super::*;

    fn info(id: &str, priority: i32, requires: &[&str]) -> ModuleInfo {
        ModuleInfo {
            folder: PathBuf::from(id),
            manifest: Manifest {
                id: id.to_string(),
                priority: Some(priority),
                requires: requires.iter().map(|r| Dependency { id: r.to_string(), ..Dependency::default() }).collect(),
                ..Manifest::default()
            },
        }
    }

    #[test]
    fn in_run_order_puts_a_dependency_before_its_dependent_even_against_priority() {
        // consumer's priority (1) is LOWER than producer's (2): a naive priority-only sort
        // would put consumer first, which is exactly the bug this function exists to not have:
        // spawn_and_run's whole shared/publish guarantee depends on this being requires-order, not
        // just declaration order.
        let infos = vec![info("consumer", 1, &["producer"]), info("producer", 2, &[])];
        let ordered = in_run_order(infos);
        let ids: Vec<&str> = ordered.iter().map(|i| i.manifest.id.as_str()).collect();
        assert_eq!(ids, vec!["producer", "consumer"]);
    }

    #[test]
    fn in_run_order_is_tolerant_of_a_cycle_and_a_missing_id() {
        let infos = vec![info("a", 1, &["b"]), info("b", 2, &["a", "missing"])];
        let ordered = in_run_order(infos);
        assert_eq!(ordered.len(), 2, "a cycle or a dangling requires id should never drop or duplicate a module");
    }

    fn contract_consumer(id: &str, priority: i32, contract: &str) -> ModuleInfo {
        ModuleInfo {
            folder: PathBuf::from(id),
            manifest: Manifest {
                id: id.to_string(),
                priority: Some(priority),
                requires: vec![Dependency { contract: contract.to_string(), ..Dependency::default() }],
                ..Manifest::default()
            },
        }
    }

    fn contract_provider(id: &str, priority: i32, contract: &str) -> ModuleInfo {
        ModuleInfo {
            folder: PathBuf::from(id),
            manifest: Manifest {
                id: id.to_string(),
                priority: Some(priority),
                provides: vec![Provision { contract: contract.to_string(), ..Provision::default() }],
                ..Manifest::default()
            },
        }
    }

    #[test]
    fn a_contract_consumer_runs_after_everything_that_provides_it() {
        // The provider is not named after the contract and the consumer never names the provider:
        // that indirection is the entire point, and it's exactly what a naive id-only walk misses.
        // Load order is set against the desired result so only the contract link can produce it.
        let infos = vec![contract_consumer("canvas", 1, "draw-commands"), contract_provider("some-director", 2, "draw-commands")];
        let ordered = in_run_order(infos);
        let ids: Vec<&str> = ordered.iter().map(|i| i.manifest.id.as_str()).collect();
        assert_eq!(ids, vec!["some-director", "canvas"], "a provider must run before its consumer, or shared state is a tick stale");
    }

    #[test]
    fn every_provider_of_a_contract_runs_before_the_consumer_not_just_one() {
        let infos = vec![
            contract_consumer("canvas", 1, "draw-commands"),
            contract_provider("world", 2, "draw-commands"),
            contract_provider("overlay", 3, "draw-commands"),
        ];
        let ordered = in_run_order(infos);
        let ids: Vec<&str> = ordered.iter().map(|i| i.manifest.id.as_str()).collect();
        assert_eq!(ids.last(), Some(&"canvas"), "the consumer gathers from all of them, so it goes last: {ids:?}");
    }

    #[test]
    fn ordering_against_a_contract_nothing_provides_is_not_an_error() {
        // The optional case, and the normal one for a project that hasn't written its director yet:
        // the canvas still runs, and simply draws nothing.
        let infos = vec![contract_consumer("canvas", 1, "draw-commands")];
        let ordered = in_run_order(infos);
        assert_eq!(ordered.len(), 1);
    }

    #[test]
    fn a_misspelled_field_is_captured_rather_than_silently_dropped() {
        // The whole point: this parses, and before `extra` existed it parsed into a module that
        // provided nothing, with nothing anywhere saying why the role never got filled.
        let m: Manifest =
            serde_json::from_str(r#"{"id":"m","name":"M","provdies":[{"contract":"draw-commands","version":"1.0.0"}]}"#).unwrap();
        assert!(m.provides.is_empty(), "the typo really does mean nothing was provided");
        assert_eq!(m.unknown_fields(), vec!["provdies"]);
    }

    #[test]
    fn a_misspelled_field_inside_requires_or_provides_is_found_too() {
        let m: Manifest = serde_json::from_str(
            r#"{"id":"m","name":"M","requires":[{"contract":"c","verison":"^1"}],"provides":[{"contract":"d","version":"1.0.0","optionl":true}]}"#,
        )
        .unwrap();
        assert_eq!(m.unknown_fields(), vec!["provides[0].optionl", "requires[0].verison"]);
    }

    #[test]
    fn a_clean_manifest_reports_no_unknown_fields() {
        let m: Manifest = serde_json::from_str(
            r#"{"id":"m","name":"M","version":"1.0.0","priority":3,"kind":"contract","description":"d","website":"w","icon":"i","requires":[{"contract":"c","version":"^1","optional":true}],"provides":[{"contract":"d","version":"1.0.0"}]}"#,
        )
        .unwrap();
        assert!(m.unknown_fields().is_empty(), "got {:?}", m.unknown_fields());
        assert_eq!(m.priority, Some(3));
        assert!(m.invalid_kind().is_none());
    }

    #[test]
    fn an_unrecognised_kind_is_reported_rather_than_treated_as_an_ordinary_module() {
        let typo: Manifest = serde_json::from_str(r#"{"id":"c","name":"C","kind":"contracts"}"#).unwrap();
        assert_eq!(typo.invalid_kind(), Some("contracts"));
        assert!(!typo.is_contract(), "which is exactly why it has to be caught: it would have been run");

        let absent: Manifest = serde_json::from_str(r#"{"id":"m","name":"M"}"#).unwrap();
        assert!(absent.invalid_kind().is_none(), "no kind at all is an ordinary module, not an error");
    }

    #[test]
    fn a_requirement_spells_out_which_kind_it_is() {
        let module: Dependency = serde_json::from_str(r#"{"module": "vector-canvas"}"#).unwrap();
        let bare: Dependency = serde_json::from_str(r#"{"id": "vector-canvas"}"#).unwrap();
        let contract: Dependency = serde_json::from_str(r#"{"contract": "draw-commands"}"#).unwrap();

        // "module" is a spelling of "id", so every manifest written before contracts existed keeps
        // resolving to exactly what it always did.
        assert_eq!(module.store_id(), "vector-canvas");
        assert_eq!(bare.store_id(), "vector-canvas");
        assert!(!module.names_contract() && !bare.names_contract());

        // A contract resolves through the same store (contracts are modules), but is read from
        // the gathered key rather than from one module's own published state.
        assert_eq!(contract.store_id(), "draw-commands");
        assert!(contract.names_contract());
    }

    #[test]
    fn run_order_agrees_with_in_run_order() {
        let a = info("consumer", 1, &["producer"]);
        let b = info("producer", 2, &[]);
        let refs = vec![&a, &b];
        let rank = run_order(&refs);
        assert!(rank["producer"] < rank["consumer"], "producer should rank before consumer, got {rank:?}");
    }
}
